apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "api-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "api-service.name" . }}
    app.kubernetes.io/instance: {{ include "api-service.instance-name" . }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - "{{ include "api-service.name" . }}.{{ .Values.appsDomain }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.route.path }}
      backendRefs:
        - name: {{ include "api-service.fullname" . }}
          port: {{ .Values.service.port }}

