apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "api-service.name" . }}
    app.kubernetes.io/instance: {{ include "api-service.instance-name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "api-service.name" . }}
    app.kubernetes.io/instance: {{ include "api-service.instance-name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}
