# Default values for web-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appsDomain: example.com
containerPort: 80
env:
  SERVICE_LOG_LEVEL: info
gateway:
  name: traefik-gateway
  namespace: traefik-system
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: nginx
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.21"
# This is to override the chart name.
nameOverride: "web-app"
# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 3
route:
  path: /
service:
  port: 80
  type: ClusterIP

