# Default values for api-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appsDomain: example.com
containerPort: 8080
env:
  SERVICE_LOG_LEVEL: info
gateway:
  name: traefik-gateway
  namespace: traefik-system
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: api-service
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.21"
# This is to override the chart name.
nameOverride: "api-service"
# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi
route:
  path: /api/
service:
  port: 8080
  type: ClusterIP

