name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**' # Triggers only when changes are made to the charts folder
  workflow_dispatch: # Allows manual triggering

jobs:
  push-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Critical: allows the GITHUB_TOKEN to push to GHCR

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Run lint
        run: ct lint --target-branch main --chart-dirs charts

      - name: Package and Push
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              helm package "$chart"
              helm push *.tgz oci://ghcr.io/${OWNER}/helm-charts
              rm *.tgz
            fi
          done
